import { Poll, Quiz } from '@/types/engagement';

export const mockPolls: Poll[] = [
  {
    id: 'poll-1',
    slug: 'ai-judging-spending-habits',
    question: 'Is AI secretly judging your spending habits?',
    options: [
      { id: 'yes', text: 'Yes', votes: 1847, percentage: 68 },
      { id: 'no', text: 'No', votes: 867, percentage: 32 }
    ],
    category: 'Technology',
    tags: ['AI', 'fintech', 'privacy'],
    relatedArticles: ['ai-financial-tracking-revolution'],
    cta: {
      text: 'Track your spending smartly',
      link: '/portfolio',
      type: 'internal'
    },
    totalVotes: 2714,
    createdAt: '2025-10-21T10:00:00Z'
  },
  {
    id: 'poll-2',
    slug: 'rbi-rate-cut-prediction',
    question: 'Will RBI cut interest rates in the next policy meeting?',
    options: [
      { id: 'yes-25', text: 'Yes, 0.25%', votes: 2340, percentage: 45 },
      { id: 'yes-50', text: 'Yes, 0.50%', votes: 1560, percentage: 30 },
      { id: 'no', text: 'No change', votes: 1300, percentage: 25 }
    ],
    category: 'Economy',
    tags: ['RBI', 'interest-rates', 'monetary-policy'],
    relatedProducts: [
      { type: 'mutualfund', id: 'debt-fund-1', name: 'HDFC Short Term Debt Fund' }
    ],
    cta: {
      text: 'Explore debt funds',
      link: '/mutual-funds?category=debt',
      type: 'internal'
    },
    totalVotes: 5200,
    createdAt: '2025-10-21T08:30:00Z'
  },
  {
    id: 'poll-3',
    slug: 'sensex-75k-target',
    question: 'Will Sensex hit 75,000 before December 2025?',
    options: [
      { id: 'yes', text: 'Yes, definitely', votes: 3200, percentage: 52 },
      { id: 'maybe', text: 'Maybe, depends on FII flows', votes: 2100, percentage: 34 },
      { id: 'no', text: 'No, correction expected', votes: 860, percentage: 14 }
    ],
    category: 'Stocks',
    tags: ['sensex', 'market-prediction', 'technical-analysis'],
    relatedArticles: ['sensex-technical-outlook-2025'],
    cta: {
      text: 'Analyze Nifty 50 stocks',
      link: '/stocks',
      type: 'internal'
    },
    totalVotes: 6160,
    createdAt: '2025-10-20T14:00:00Z',
    expiresAt: '2025-12-31T23:59:59Z'
  },
  {
    id: 'poll-4',
    slug: 'crypto-regulation-impact',
    question: 'How will new crypto regulations impact your investment strategy?',
    options: [
      { id: 'increase', text: 'Increase crypto allocation', votes: 890, percentage: 28 },
      { id: 'decrease', text: 'Reduce exposure', votes: 1456, percentage: 46 },
      { id: 'no-change', text: 'No change', votes: 824, percentage: 26 }
    ],
    category: 'Crypto',
    tags: ['cryptocurrency', 'regulation', 'investment-strategy'],
    relatedProducts: [
      { type: 'crypto', id: 'bitcoin', name: 'Bitcoin' },
      { type: 'crypto', id: 'ethereum', name: 'Ethereum' }
    ],
    cta: {
      text: 'Explore crypto market',
      link: '/crypto',
      type: 'internal'
    },
    totalVotes: 3170,
    createdAt: '2025-10-21T06:15:00Z',
    sponsored: {
      by: 'CoinDCX',
      logo: '/sponsors/coindcx.png'
    }
  }
];

export const mockQuizzes: Quiz[] = [
  {
    id: 'quiz-1',
    slug: 'mutual-funds-basics',
    title: 'Mutual Funds 101: Test Your Knowledge',
    description: 'How well do you understand mutual fund investing? Take this quiz to find out!',
    category: 'Mutual Funds',
    tags: ['mutual-funds', 'basics', 'investing'],
    difficulty: 'beginner',
    pointsReward: 30,
    questions: [
      {
        id: 'q1',
        question: 'What is the expense ratio in a mutual fund?',
        options: [
          'The fee charged by the fund manager',
          'The return generated by the fund',
          'The NAV of the fund',
          'The exit load percentage'
        ],
        correctAnswer: 0,
        explanation: 'Expense ratio represents the annual fee charged by the fund house for managing your investments, expressed as a percentage of assets.',
        points: 10
      },
      {
        id: 'q2',
        question: 'Which type of mutual fund is considered least risky?',
        options: [
          'Equity funds',
          'Debt funds',
          'Hybrid funds',
          'Sector funds'
        ],
        correctAnswer: 1,
        explanation: 'Debt funds invest primarily in fixed-income securities like bonds and government securities, making them less volatile than equity funds.',
        points: 10
      },
      {
        id: 'q3',
        question: 'What does SIP stand for in mutual fund investing?',
        options: [
          'Single Investment Plan',
          'Systematic Investment Plan',
          'Simple Interest Portfolio',
          'Secured Investment Product'
        ],
        correctAnswer: 1,
        explanation: 'SIP (Systematic Investment Plan) allows you to invest a fixed amount regularly in a mutual fund scheme, helping with rupee cost averaging.',
        points: 10
      }
    ],
    relatedArticles: ['mutual-funds-beginner-guide'],
    cta: {
      text: 'Explore top mutual funds',
      link: '/mutual-funds'
    },
    completionCount: 5680,
    averageScore: 76,
    createdAt: '2025-10-20T09:00:00Z'
  },
  {
    id: 'quiz-2',
    slug: 'ipo-investment-expert',
    title: 'IPO Investment Strategy Quiz',
    description: 'Are you ready to invest in IPOs? Test your understanding of primary market investments.',
    category: 'IPO',
    tags: ['ipo', 'primary-market', 'investing'],
    difficulty: 'intermediate',
    pointsReward: 50,
    questions: [
      {
        id: 'q1',
        question: 'What is the minimum investment required for retail investors in an IPO?',
        options: [
          '₹10,000',
          '₹15,000',
          'One lot (varies by IPO)',
          '₹50,000'
        ],
        correctAnswer: 2,
        explanation: 'The minimum investment is one lot, which varies for each IPO. The lot size is determined by the company and mentioned in the IPO prospectus.',
        points: 15
      },
      {
        id: 'q2',
        question: 'What does "listing gain" mean in IPO investing?',
        options: [
          'Profit from selling on listing day',
          'Dividend received after listing',
          'Bonus shares given',
          'Tax benefit on IPO investment'
        ],
        correctAnswer: 0,
        explanation: 'Listing gain is the profit made when you sell IPO shares on the listing day at a price higher than the issue price.',
        points: 15
      },
      {
        id: 'q3',
        question: 'Which factor is MOST important when evaluating an IPO?',
        options: [
          'Company logo design',
          'Business fundamentals and financials',
          'Celebrity endorsements',
          'Number of shares offered'
        ],
        correctAnswer: 1,
        explanation: 'Business fundamentals, financial performance, industry position, and growth prospects are crucial for evaluating IPO investment potential.',
        points: 20
      }
    ],
    relatedArticles: ['ipo-investment-guide-2025'],
    relatedProducts: [
      { type: 'stock', id: 'upcoming-ipo-1', name: 'TechCorp IPO' }
    ],
    cta: {
      text: 'View upcoming IPOs',
      link: '/research/ipo'
    },
    completionCount: 3420,
    averageScore: 68,
    createdAt: '2025-10-19T11:00:00Z'
  },
  {
    id: 'quiz-3',
    slug: 'crypto-trading-advanced',
    title: 'Advanced Crypto Trading Quiz',
    description: 'Think you know cryptocurrency trading? Prove your expertise!',
    category: 'Crypto',
    tags: ['cryptocurrency', 'trading', 'blockchain'],
    difficulty: 'expert',
    pointsReward: 75,
    questions: [
      {
        id: 'q1',
        question: 'What is the purpose of "gas fees" in Ethereum transactions?',
        options: [
          'To heat up mining equipment',
          'To compensate miners for computational work',
          'To buy gasoline for transport',
          'To increase transaction speed only'
        ],
        correctAnswer: 1,
        explanation: 'Gas fees compensate miners/validators for the computational resources used to process and validate transactions on the Ethereum network.',
        points: 25
      },
      {
        id: 'q2',
        question: 'What does "HODL" originally stand for in crypto communities?',
        options: [
          'Hold On for Dear Life',
          'A misspelling of "hold"',
          'High Order Digital Ledger',
          'Hedge Only During Losses'
        ],
        correctAnswer: 1,
        explanation: 'HODL originated from a typo in a 2013 Bitcoin forum post where someone misspelled "hold". It later became a backronym for "Hold On for Dear Life".',
        points: 25
      },
      {
        id: 'q3',
        question: 'Which consensus mechanism does Bitcoin use?',
        options: [
          'Proof of Stake',
          'Proof of Work',
          'Delegated Proof of Stake',
          'Proof of Authority'
        ],
        correctAnswer: 1,
        explanation: 'Bitcoin uses Proof of Work (PoW), where miners compete to solve complex mathematical problems to validate transactions and add blocks to the blockchain.',
        points: 25
      }
    ],
    relatedArticles: ['crypto-trading-strategies-2025'],
    cta: {
      text: 'Start crypto trading',
      link: '/crypto'
    },
    completionCount: 1240,
    averageScore: 54,
    createdAt: '2025-10-18T15:30:00Z',
    sponsored: {
      by: 'WazirX',
      logo: '/sponsors/wazirx.png'
    }
  }
];
